# Generated by Django 4.0.1 on 2022-02-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
